### ISSUE TITLE
Differences with "sn-cicd-example"

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd-example-v3#1]
Feature wise, any new compare with previous project "sn-cicd-example"?

**Comment by bmoers** [comment]
This is an example project using the new sn-cicd V3 https://github.com/bmoers/sn-cicd/tree/release/3 (not merged with master yet as it needs documentation).
To get this running just rename 'example.env' to '.env' and run npm install && npm start

**Comment by gitlabbin** [comment]
will test out, close this one
