### ISSUE TITLE
Pull request not triggering

### ISSUE THREAD

**Issue by Anjali1425** [bmoers/sn-cicd-example-v3#5]
Thanks for creating the server and making it opensource :)
I am Trying to build the application, but the pull request is not triggering. 
The logs says "master is not enabled,  Skip export." Could you please point out what could be the reason for this. 
Thanks!!
![tempsnip](https://user-images.githubusercontent.com/40041792/62354014-c26aa400-b4c0-11e9-9cc6-ce31ec55cc12.png)

**Comment by bmoers** [comment]
Looks like the master host name is missing.

This can be either configured in the REST request from ServiceNow to the CICD server (requires to add this to the request : { master : { name: 'https://dev99999.service-now.com' })

Or add the source -> master mapping in the .env file 

```
# master source definition CICD_GIT_MASTER_SOURCE_[INSTANCENAME] (instance short name)
# this reads: if source is 'development.service-now.com', use 'prod.service-now.com' as the master
CICD_GIT_MASTER_SOURCE_DEVELOPMENT=prod.service-now.com
```

e.g. if the dev hostname is dev11111.service-now.com and the production (master) env is https://dev99999.service-now.com, add following :
CICD_GIT_MASTER_SOURCE_DEV11111=dev99999.service-now.com

The 'master' environment is used to create the git repo during the first run or update the master branch in any further runs.
