### ISSUE TITLE
Getting error while pushing data to GIT

### ISSUE THREAD

**Issue by mua32** [bmoers/sn-cicd-example-v3#6]
'Command failed: git add "C:\\Users\\SHUVAR~1\\AppData\\Local\\Temp\\git-root\\5ab205bc-8f74-4cd1-800c-a3aeaa96367b\\us\\global\\sys_update_set_76658483dbd37300e76e771c8c9619c3.xml"\nfatal: C:\\Users\\SHUVAR~1\\AppData\\Local\\Temp\\git-root\\5ab205bc-8f74-4cd1-800c-a3aeaa96367b\\us\\global\\sys_update_set_76658483dbd37300e76e771c8c9619c3.xml: \'C:\\Users\\SHUVAR~1\\AppData\\Local\\Temp\\git-root\\5ab205bc-8f74-4cd1-800c-a3aeaa96367b\\us\\global\\sys_update_set_76658483dbd37300e76e771c8c9619c3.xml\' is outside repository\n'

Getting above error when trying to push the data from update set to GIT through CICD.

**Comment by bmoers** [comment]
On Windows there an issue with git and the 2 different ways of defining the path (C:\Users\SHUVAR1\AppData\Local\Temp vs C:\Users\SHUVAR~1\AppData\Local\Temp)

To solve this issue, un-comment following variables and set it to a path in the .env 
```
# directory to place the ServiceNow code extraction [temp/git-root]
#CICD_CODE_DIRECTORY=C:/temp/repos
# temp directory for zip extraction [temp/temp-build]
#CICD_TEMP_DIRECTORY=C:/temp/temp-build
# build results directory (static exposed under /doc) [temp/doc-root]
#CICD_DOC_DIRECTORY=C:/temp/doc-root
```
Please let me know if issue is solved.

**Comment by mua32** [comment]
Thanks,really appreciate your help.The issue got resolved.
